# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtypes',
        ),
    ]
